CREATE ROLE "kie-user" WITH
    LOGIN
    SUPERUSER
    INHERIT
    CREATEDB
    CREATEROLE
    NOREPLICATION
    PASSWORD 'kie-pass';

GRANT ALL PRIVILEGES ON DATABASE postgres TO "kie-user";
GRANT ALL PRIVILEGES ON DATABASE kie TO "kie-user";
GRANT ALL PRIVILEGES ON DATABASE kie TO postgres;