services:
  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/free:latest-lite
    restart: no
    environment:
      ORACLE_PWD: "Password123456"
      ORACLE_USER: system
    ports:
      - "1521:1521" 

  process-persistence-service:
    container_name: process-persistence-service
    image: dev.local/bamoe/process-persistence-oracle:${PROJECT_VERSION}
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      QUARKUS_DATASOURCE_DB_KIND: oracle
      QUARKUS_DATASOURCE_USERNAME: system
      QUARKUS_DATASOURCE_PASSWORD: Password123456
      QUARKUS_DATASOURCE_JDBC_DRIVER: oracle.jdbc.OracleDriver
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:oracle:thin:@//oracle:1521/FREEPDB1"
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      KOGITO_JOBS_SERVICE_URL: http://127.0.0.1:8080
      KOGITO_SERVICE_URL: http://127.0.0.1:8080
      KOGITO_DATAINDEX_HTTP_URL: http://127.0.0.1:8080
      JAVA_DEBUG: true
      JAVA_DEBUG_PORT: "*:5005"
