services:
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: no
    hostname: mssql-host
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Pass@123"
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "mssql-host", "-U", "sa", "-P", "Pass@123", "-No", "-Q", "SELECT 1" ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools:latest
    restart: no
    command: "/opt/mssql-tools/bin/sqlcmd -S mssql-host -l 60 -U sa -P 'Pass@123' -d master -i /tmp/init.sql"
    depends_on:
      mssql:
        condition: service_healthy
    volumes:
      - ./sql/mssql/init.sql:/tmp/init.sql

  process-persistence-service:
    container_name: process-persistence-service
    image: dev.local/bamoe/process-persistence-mssql:${PROJECT_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      QUARKUS_HTTP_CORS_ORIGINS: "/.*/"
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:sqlserver://mssql-host:1433;DatabaseName=bamoe;encrypt=true;trustServerCertificate=true;"
      QUARKUS_DATASOURCE_USERNAME: sa
      QUARKUS_DATASOURCE_PASSWORD: 'Pass@123'
      QUARKUS_DATASOURCE_DB_KIND: mssql
      KOGITO_JOBS_SERVICE_URL: http://127.0.0.1:8080
      KOGITO_SERVICE_URL: http://127.0.0.1:8080
      KOGITO_DATAINDEX_HTTP_URL: http://127.0.0.1:8080
    extra_hosts:
      - "127.0.0.1:host-gateway"
